apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  test: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlcy5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDM1L3Bvc3RncmVzP3NzbG1vZGU9ZGlzYWJsZQ==
  pass: cG9zdGdyZXM=