apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-golang-yaml
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amserdion01/argogolang.git
    targetRevesion: main
    path: golang
  destination:
    server: https://kubernetes.default.svc
    namespace: argogolangyaml

  syncPolicy: 
    syncOptions:
      - CreateNamespace=true
  
    automated:
      selfHeal: true
      prune: true