apiVersion: apps/v1
kind: Deployment

metadata:
  #namespace: postgres
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                key:  pass
                name: db-secret
          - name: POSTGRES_USER
            valueFrom: 
              configMapKeyRef:
                key:  db_val
                name: data-config
          - name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef:
                key:  db_val
                name: data-config
